name: Release

# Controls when the workflow will run
on:
  # Only release when new commits are pushed to release branch
  push:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v3.0.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Add wasm build target
        run: rustup target add wasm32-unknown-unknown

      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host="${{ secrets.WDEPLOY_URL }}"
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

      - name: Setup env, build and deploy
        run: |
          export WDEPLOY_USER="${{ secrets.WDEPLOY_USER }}"
          export WDEPLOY_PASS="${{ secrets.WDEPLOY_PASS }}"
          export WDEPLOY_URL="${{ secrets.WDEPLOY_URL }}"
          export WDEPLOY_PATH="${{ secrets.WDEPLOY_PATH }}"
          export WTEXT_DEPLOY_PATH="${{ secrets.WTEXT_DEPLOY_PATH }}"
          npm ci
          ./deploy.sh normal

